Repository jenkins-infra/cn.jenkins.io, pull requests merged in 2018-10, with the labels that each got.

#11 blog translation of hacktoberfeest
  content/blog/2018/10/2018-10-01-hacktoberfest.adoc
Labels: hacktoberfest

#19 No need to translate Jenkins
  content/blog/2018/03/2018-03-05-jenkins-world-talk-proposal-tips.adoc
  content/index.html.haml
Labels: hacktoberfest

#44 artwork page translation
  content/artwork/index.html.haml
Labels: hacktoberfest, ready-for-merge

#37 add node as new member
  content/sigs/chinese-localization/index.adoc
Labels: ready-for-merge

#28 translate into Chiense: content/projects/index #25
  content/projects/index.adoc
Labels: hacktoberfest, ready-for-merge

#23 translate into Chinese: content/projects/remoting #22
  content/projects/remoting.adoc
Labels: hacktoberfest, ready-for-merge

#48 translation for abourt/press
  content/press.adoc
Labels: hacktoberfest, ready-for-merge

#51 Add pull-template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest

#32 translate into Chinese: content/projects/gsoc #26
  content/projects/gsoc.adoc
Labels: hacktoberfest, ready-for-merge

#33 translate into Chinese: content/projects/blueocean #27
  content/projects/blueocean/index.html.haml
  content/projects/blueocean/roadmap/index.html.haml
Labels: hacktoberfest, ready-for-merge

#49 Add localization for content/solutions/java.adoc
  content/solutions/java.adoc
Labels: hacktoberfest, ready-for-merge

#52 Translate into Chinese:content/download #50
  content/download/index.html.haml
  content/download/lts.adoc
  content/download/mirrors.adoc
  content/download/thank-you-downloading-osx-installer-stable.html.haml
  content/download/thank-you-downloading-osx-installer.html.haml
  content/download/thank-you-downloading-windows-installer-stable.html.haml
  content/download/thank-you-downloading-windows-installer.html.haml
Labels: hacktoberfest, ready-for-merge

#54 add encoding declaration UTF-8
  content/sigs/chinese-localization/index.adoc
Labels: hacktoberfest, ready-for-merge

#61 调整一下 about 导航栏的译法
  content/_messages/messages_zh-CN.yml
  content/artwork/index.html.haml
Labels: hacktoberfest, ready-for-merge

#63 Add execute permission for script files
  scripts/asciidoctor-pdf
  scripts/awestruct
  scripts/blobxfer
  scripts/crushinator.sh
  scripts/datadir.rb
  scripts/fetch-examples
  scripts/fetch-external-resources
  scripts/generate-handbook-pdf
  scripts/groovy
  scripts/node
  scripts/partial.rb
  scripts/release.rss.groovy
  scripts/ruby
  scripts/user-site-deploy.sh
Labels: hacktoberfest
