Repository jenkins-infra/cn.jenkins.io, pull requests merged in 2021-02, with the labels that each got.

#323 Add owners file
  OWNERS
  content/_data/changelogs/OWNERS
Labels: size/XS

#322 add weekly changelog 2.277 & lts changelog 2.263.3
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: do-not-merge/hold, lgtm, size/L

#324 add weekly changelog 2.278
  content/_data/changelogs/weekly.yml
  content/doc/upgrade-guide/2.263.adoc
Labels: lgtm, size/M

#325 Delete original english changelog in weekly changelog 2.278 & and weekly changelog 2.279
  content/_data/changelogs/weekly.yml
Labels: lgtm, size/M

#326 add weekly changelog 2.280 & lts changelog 2.263.4
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/doc/upgrade-guide/2.263.adoc
Labels: lgtm, ok-to-test
